settings:
    lib_name: inverter_sky130_tt_1v80_025C_pex
    units:
        time: ns
        voltage: V
        capacitive_load: pF
        leakage_power: nW
        energy: fJ
    named_nodes:
        primary_power:
            name: VDD
            voltage: 1.8
        primary_ground:
            name: VSS
            voltage: 0
    logic_thresholds:
        low: 0.2
        high: 0.8
        rising: 0.5
        falling: 0.5
    temperature: 27
    cell_defaults:
    models:
      - "config/mc_switches.spice"
      - "sky130A/libs.tech/ngspice/sky130.lib.spice tt"
    simulation:
        backend: ngspice-subprocess
    debug: true
    debug_dir: debug_out

cells:
    buf:
        netlist: "cells/buf_pex.spice"
        inputs: [A]
        outputs: [X]
        functions: ["X = A"]
        area: 13.884